name       : breeze-cursor-theme
version    : 5.16.1
release    : 10
source     :
    - https://download.kde.org/stable/plasma/5.16.1/breeze-5.16.1.tar.xz : bf4fba98f83311365f249d706689f327380db2de61ca7bb2a8442472e0b1316e
license    : GPL-2.0
component  : desktop.theme
summary    : Breeze cursor theme
description: |
    Breeze cursor theme
install    : |
    breezeDir=$installdir/usr/share/icons/breeze-cursor
    install -dm00755 $breezeDir/
    cp -R $workdir/cursors/Breeze/Breeze/* $breezeDir/
    # Provide shared link for budgie + mate desktop branding
    install -D -m 00644 $pkgfiles/index.theme $installdir/usr/share/icons/default/index.theme
