name       : breeze-cursor-theme
version    : 5.15.4.1
release    : 7
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.4/breeze-5.15.4.1.tar.xz : 9a95fb9c5be7c84164d3ce337d15cad57cdd495fe84e1da8487a463d69293497
license    : GPL-2.0
component  : desktop.theme
summary    : Breeze cursor theme
description: |
    Breeze cursor theme
install    : |
    breezeDir=$installdir/usr/share/icons/breeze-cursor
    install -dm00755 $breezeDir/
    cp -R $workdir/cursors/Breeze/Breeze/* $breezeDir/
    # Provide shared link for budgie + mate desktop branding
    install -D -m 00644 $pkgfiles/index.theme $installdir/usr/share/icons/default/index.theme
