name       : breeze-cursor-theme
version    : 5.16.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.0/breeze-5.16.0.tar.xz : eb37e75b6a463648edd1b421e06531054a361af9b60e0e4fb1588a36212a4dae
license    : GPL-2.0
component  : desktop.theme
summary    : Breeze cursor theme
description: |
    Breeze cursor theme
install    : |
    breezeDir=$installdir/usr/share/icons/breeze-cursor
    install -dm00755 $breezeDir/
    cp -R $workdir/cursors/Breeze/Breeze/* $breezeDir/
    # Provide shared link for budgie + mate desktop branding
    install -D -m 00644 $pkgfiles/index.theme $installdir/usr/share/icons/default/index.theme
