name       : breeze-cursor-theme
version    : 5.6.1
release    : 1
source     :
    - http://stroblindustries.com/solus-tarballs/breeze-cursor-theme-5.6.1.tar.xz : f10a45c3f27a02c74ea862e16d91f8d5cf25396a78fe285769a5fbbbaad2ba2d
license    : GPL-2.0
component  : desktop
summary    : Breeze cursor theme
description: |
    Breeze cursor theme
install    : |
    breezeDir=$installdir/usr/share/icons/breeze-cursor
    install -dm755 $breezeDir/
    cp -R $srcdir/* $breezeDir/
